### ISSUE TITLE
Potential IP spoofing vulnerability with AWS ELB (x-forwarded-for)

### ISSUE THREAD

**Issue by rinogo** [neekware/fullerstack#4]
Before diving in, I should mention that I haven't used `nax-ipware`, but while reading up on it, I noticed something that could be an issue.

It seems that the `nax-ipware` makes some assumptions that might not be correct. Amazon's [docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-for) state:

> Elastic Load Balancing stores the IP address of the client in the X-Forwarded-For request header and passes the header to your server. If the X-Forwarded-For request header is not included in the request, the load balancer creates one with the client IP address as the request value. Otherwise, the load balancer appends the client IP address to the existing header and passes the header to your server. The X-Forwarded-For request header may contain multiple IP addresses that are comma separated. The left-most address is the client IP where the request was first made. This is followed by any subsequent proxy identifiers, in a chain.

This isn't written very clearly - with regard to spoofing, we're concerned with the case in which the X-Forwarded-For request header *is* included in the request (the "Otherwise..." sentence above).

In this case, the client's IP address is *not* the leftmost. However, regarding `X_FORWARDED_FOR `, `nax-ipware`'s docs state:

> Load balancers or proxies such as AWS ELB (default client is `left-most` [`<client>, <proxy1>, <proxy2>`])

Some experimentation confirms that the client's IP address is not left-most in the case in which the header is provided. I added a spoofed IP address to the header in question in my test app using the following:

```
xhr.setRequestHeader('x-forwarded-for', '111.111.111.111');
```

Once the request comes in to my app from ELB, the `x-forwarded-for` header value is "111.111.111.111, w.x.y.z", where "w.x.y.z" is my actual client's IP address.

Am I misinterpreting the `nax-ipware` docs? It seems that the quote from the docs above might be more accurately written as:
> Load balancers or proxies such as AWS ELB (default client is `left-most` [`<client>, <proxy1>, <proxy2>`]), but only if the header was originally empty.

It seems that if there's a chain of proxies *and* a forged `x-forwarded-for` header, the value of the header would really be something like `<forged>, <client>, <proxy1>, <proxy2>`.

Are you seeing things differently on your end? Looking forward to hearing your thoughts on this - seems there's some disagreement/confusion online due to the clumsy wording of the AWS docs.

**Comment by un33k** [comment]
@rinogo `nax-ipware` doesn't detect ip spoofing out of the box. However, it can be configured to detect it.

- When `X-Forwarded-For` is detected, the initial order is `left-most` as per
  - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For 
  - You can change this behaviour by passing in `right-most` as the `order` of ips
  - https://github.com/neekware/fullerstack/blob/04d63fed73e9424eb5133048e725fd36b6ee809d/libs/nax-ipware/src/lib/ipware.model.ts#L23
  
- Spoofing is possible when one of the proxies is rouge 
  - Use trusted proxies, along with proxy count, to bring "trust" to your connection path
 
> It seems that `<forged>, <client>, <proxy1>, <proxy2>`, is coming through proxies, and the last proxy is not `trusted`, otherwise, it wouldn't have injected a bad ip address. 

Please have a look at the test cases! all scenarios have been covered.  If a test doesn't provide proper `options`, but injects spoofed data, `ipware` will happily report the spoofed data.  So, pass the proper `options` in.

Feel free to raise PRs should you find a bug! If they are security related, you can email the issue instead of raising an issue.

Hope this helps
